"""CLI surface: JSON output shape, --fail-on-drift exit codes, check subcommand."""

from __future__ import annotations

import json
import os
from pathlib import Path

from protodrift.cli import main

T = 1_700_000_000.0
GO_STUB = "// Code generated by protoc-gen-go. DO NOT EDIT.\n//\tsource: {proto}\n"


def write(root: Path, rel: str, text: str, mtime: float = T) -> Path:
    path = root / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    os.utime(path, (mtime, mtime))
    return path


def drift_tree(root: Path) -> Path:
    """Two protos, Go stubs for both, order.proto newer than its stub, Python stub for user only."""
    for name in ("user", "order"):
        write(root, f"api/v1/{name}.proto", 'syntax = "proto3";\n', T - 60)
        write(root, f"sdk/go/{name}.pb.go", GO_STUB.format(proto=f"api/v1/{name}.proto"), T)
    write(root, "api/v1/order.proto", 'syntax = "proto3";\n', T + 60)
    write(root, "sdk/py/user_pb2.py", "# generated\n", T)
    return root


def clean_tree(root: Path) -> Path:
    """Same tree with the stale proto touched back and the missing Python stub added."""
    drift_tree(root)
    write(root, "api/v1/order.proto", 'syntax = "proto3";\n', T - 60)
    write(root, "sdk/py/order_pb2.py", "# generated\n", T)
    return root


def test_scan_json_is_parseable(tmp_path, capsys):
    drift_tree(tmp_path)
    assert main(["scan", str(tmp_path), "--json"]) == 0
    payload = json.loads(capsys.readouterr().out)
    assert payload["drift_count"] > 0
    assert {"stale", "missing_sdk"} <= {f["type"] for f in payload["findings"]}
    severities = {f["type"]: f["severity"] for f in payload["findings"]}
    assert severities["stale"] == "CRITICAL"
    assert severities["missing_sdk"] == "HIGH"


def test_clean_tree_exits_zero(tmp_path, capsys):
    clean_tree(tmp_path)
    assert main(["scan", str(tmp_path), "--fail-on-drift"]) == 0
    assert "No proto drift detected" in capsys.readouterr().out


def test_fail_on_drift_exits_non_zero(tmp_path, capsys):
    drift_tree(tmp_path)
    assert main(["scan", str(tmp_path), "--fail-on-drift"]) == 1
    assert "CRITICAL" in capsys.readouterr().out
    assert main(["scan", str(tmp_path)]) == 0  # same drift, no gating
    capsys.readouterr()


def test_config_gates_can_disable_every_type(tmp_path, capsys):
    drift_tree(tmp_path)
    write(tmp_path, ".proto-drift.toml",
          "[fail]\non_stale = false\non_missing_sdk = false\non_orphan = false\n", T)
    assert main(["scan", str(tmp_path), "--fail-on-drift"]) == 0
    assert "CRITICAL" in capsys.readouterr().out  # still reported, just not gating


def test_check_honours_fail_gates(tmp_path, capsys):
    drift_tree(tmp_path)
    write(tmp_path, ".proto-drift.toml",
          "[fail]\non_stale = false\non_missing_sdk = false\non_orphan = false\n", T)
    assert main(["check", "--proto", "api/v1/order.proto", "--sdk", "sdk/go",
                 "--root", str(tmp_path), "--fail-on-drift"]) == 0
    assert "CRITICAL" in capsys.readouterr().out  # still reported, just not gating


def test_check_reports_drift_for_one_proto(tmp_path, capsys):
    drift_tree(tmp_path)
    assert main(["check", "--proto", "api/v1/order.proto", "--sdk", "sdk/go",
                 "--root", str(tmp_path), "--fail-on-drift"]) == 1
    assert "api/v1/order.proto -> sdk/go/order.pb.go" in capsys.readouterr().out


def test_check_clean_pair_is_quiet(tmp_path, capsys):
    drift_tree(tmp_path)
    assert main(["check", "--proto", "api/v1/user.proto", "--sdk", "sdk/go", "--root", str(tmp_path)]) == 0
    assert "No proto drift detected" in capsys.readouterr().out


def test_check_ambiguous_stub_is_not_missing_sdk(tmp_path, capsys):
    # Both .proto files match user_pb2.py's stem, so the stub cannot be mapped --
    # "no generated stub" would be false, the stub is right there (#14).
    for rel in ("a/user.proto", "b/user.proto"):
        write(tmp_path, rel, 'syntax = "proto3";\n')
    write(tmp_path, "sdk/py/user_pb2.py", "# generated\n")
    assert main(["check", "--proto", "a/user.proto", "--sdk", "sdk/py",
                 "--root", str(tmp_path)]) == 0
    assert "No proto drift detected" in capsys.readouterr().out


def test_check_reports_missing_sdk_for_pair(tmp_path, capsys):
    drift_tree(tmp_path)
    assert main(["check", "--proto", "api/v1/order.proto", "--sdk", "sdk/py", "--root", str(tmp_path)]) == 0
    assert "no generated stub for this proto under sdk/py" in capsys.readouterr().out


def test_check_bad_paths_are_usage_errors(tmp_path, capsys):
    drift_tree(tmp_path)
    root = str(tmp_path)
    assert main(["check", "--proto", "api/v1/nope.proto", "--sdk", "sdk/go", "--root", root]) == 2
    assert "proto not found: api/v1/nope.proto" in capsys.readouterr().err
    assert main(["check", "--proto", "api/v1/user.proto", "--sdk", "sdk/nope", "--root", root]) == 2
    assert "sdk not found: sdk/nope" in capsys.readouterr().err
    assert main(["check", "--proto", "api/v1/user.proto", "--sdk", "sdk/go", "--root", "nope"]) == 2
    assert "root not found: nope" in capsys.readouterr().err


def test_scan_without_path_uses_cwd(tmp_path, capsys, monkeypatch):
    drift_tree(tmp_path)
    monkeypatch.chdir(tmp_path)
    assert main(["scan", "--json"]) == 0
    assert json.loads(capsys.readouterr().out)["root"] == str(tmp_path.resolve())


def test_scan_bad_root_is_a_usage_error(tmp_path, capsys):
    assert main(["scan", str(tmp_path / "nope")]) == 2
    assert "not found" in capsys.readouterr().err