"""Drift detection rules: header mapping, stale/orphan/missing-SDK, clean tree."""

from __future__ import annotations

import os
from pathlib import Path

from protodrift.scan import discover, map_stub, scan, stub_stem

T = 1_700_000_000.0

GO_STUB = "// Code generated by protoc-gen-go. DO NOT EDIT.\n//\tsource: api/v1/user.proto\n\npackage userpb\n"
TS_STUB = '// @generated by ts-proto. DO NOT EDIT.\n// source: "api/v1/user.proto"\n'
PY_STUB = "# -*- coding: utf-8 -*-\n# Generated by the protocol buffer compiler.  DO NOT EDIT!\n"
RS_STUB = "// This file is @generated by prost-build.\npub struct User;\n"
PLAIN_RS = "pub struct Handwritten;\n"
NO_HEADER = "export const nothing = 1;\n"


def write(path: Path, text: str, mtime: float = T) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    os.utime(path, (mtime, mtime))
    return path


def types(root: Path) -> set[str]:
    return {f.type for f in scan(root)}


# --- stem conventions -------------------------------------------------------


def test_stub_stem_conventions():
    assert stub_stem("user.pb.go") == "user"
    assert stub_stem("user_pb2.py") == "user"
    assert stub_stem("user_pb2_grpc.py") == "user"
    assert stub_stem("user_pb.js") == "user"
    assert stub_stem("user_pb.d.ts") == "user"
    assert stub_stem("user_pb.ts") == "user"
    assert stub_stem("user.rs") == "user"


# --- source path extraction -------------------------------------------------


def test_source_extracted_from_go_header(tmp_path):
    write(tmp_path / "api/v1/user.proto", 'syntax = "proto3";\n')
    stub = write(tmp_path / "sdk/go/user.pb.go", GO_STUB)
    assert map_stub(discover(tmp_path), stub).proto == tmp_path / "api/v1/user.proto"


def test_source_extracted_from_quoted_header(tmp_path):
    write(tmp_path / "api/v1/user.proto", 'syntax = "proto3";\n')
    stub = write(tmp_path / "sdk/ts/user_pb.js", TS_STUB)
    assert map_stub(discover(tmp_path), stub).proto == tmp_path / "api/v1/user.proto"


def test_source_falls_back_to_filename_without_header(tmp_path):
    write(tmp_path / "api/v1/user.proto", 'syntax = "proto3";\n')
    stub = write(tmp_path / "sdk/py/user_pb2.py", PY_STUB)
    mapped = map_stub(discover(tmp_path), stub)
    assert mapped.proto == tmp_path / "api/v1/user.proto"
    assert mapped.reason == "convention"


def test_handwritten_rust_is_not_a_stub(tmp_path):
    write(tmp_path / "api/v1/user.proto", 'syntax = "proto3";\n')
    write(tmp_path / "sdk/rust/handwritten.rs", PLAIN_RS)
    assert discover(tmp_path).stubs == []


# --- stale ------------------------------------------------------------------


def test_stale_fires_when_proto_is_newer(tmp_path):
    write(tmp_path / "api/v1/user.proto", 'syntax = "proto3";\n')
    write(tmp_path / "sdk/go/user.pb.go", GO_STUB, mtime=T)
    write(tmp_path / "api/v1/user.proto", 'syntax = "proto3";\n', mtime=T + 60)
    assert types(tmp_path) == {"stale"}


def test_no_stale_when_stub_is_newer(tmp_path):
    write(tmp_path / "api/v1/user.proto", 'syntax = "proto3";\n', mtime=T)
    write(tmp_path / "sdk/go/user.pb.go", GO_STUB, mtime=T + 60)
    assert scan(tmp_path) == []


# --- orphan -----------------------------------------------------------------


def test_orphan_fires_when_source_proto_is_gone(tmp_path):
    write(tmp_path / "api/v1/other.proto", 'syntax = "proto3";\n')
    write(tmp_path / "sdk/go/other.pb.go", GO_STUB.replace("user", "other"), mtime=T + 60)
    write(tmp_path / "sdk/go/user.pb.go", GO_STUB)
    orphans = [f for f in scan(tmp_path) if f.type == "orphan"]
    assert [(f.language, f.stub, f.proto) for f in orphans] == [("go", "sdk/go/user.pb.go", "")]


def test_ambiguous_stem_is_not_reported_as_orphan(tmp_path):
    write(tmp_path / "a/user.proto", 'syntax = "proto3";\n')
    write(tmp_path / "b/user.proto", 'syntax = "proto3";\n')
    write(tmp_path / "sdk/py/user_pb2.py", PY_STUB)
    assert map_stub(discover(tmp_path), tmp_path / "sdk/py/user_pb2.py").ambiguous is True
    assert "orphan" not in types(tmp_path)


def test_ambiguous_stub_is_not_reported_as_missing_sdk(tmp_path):
    # The python stub is on disk; its stem is ambiguous, so which .proto it belongs
    # to cannot be decided -- python must not be claimed absent (#14).
    write(tmp_path / "a/user.proto", 'syntax = "proto3";\n')
    write(tmp_path / "b/user.proto", 'syntax = "proto3";\n')
    write(tmp_path / "sdk/py/user_pb2.py", PY_STUB)
    assert scan(tmp_path) == []


def test_ambiguous_stub_does_not_mask_a_really_missing_language(tmp_path):
    write(tmp_path / "a/user.proto", 'syntax = "proto3";\n', mtime=T)
    write(tmp_path / "b/user.proto", 'syntax = "proto3";\n', mtime=T)
    write(tmp_path / "api/v1/order.proto", 'syntax = "proto3";\n', mtime=T)
    write(tmp_path / "sdk/py/user_pb2.py", PY_STUB, mtime=T + 60)  # ambiguous python
    write(tmp_path / "sdk/go/user.pb.go",  # decidable go stub, for a/user.proto only
          GO_STUB.replace("api/v1/user.proto", "a/user.proto"), mtime=T + 60)
    assert [(f.language, f.proto) for f in scan(tmp_path)] == [
        ("go", "api/v1/order.proto"),
        ("go", "b/user.proto"),
    ]


# --- missing SDK ------------------------------------------------------------


def test_missing_sdk_for_a_represented_language(tmp_path):
    # Python is represented (user_pb2.py) but order.proto has no Python stub.
    write(tmp_path / "api/v1/user.proto", 'syntax = "proto3";\n', mtime=T)
    write(tmp_path / "api/v1/order.proto", 'syntax = "proto3";\n', mtime=T)
    for name in ("user", "order"):
        write(tmp_path / f"sdk/go/{name}.pb.go", GO_STUB.replace("user", name), mtime=T + 60)
    write(tmp_path / "sdk/py/user_pb2.py", PY_STUB, mtime=T + 60)
    findings = [f for f in scan(tmp_path) if f.type == "missing_sdk"]
    assert [(f.language, f.proto) for f in findings] == [("python", "api/v1/order.proto")]
    assert findings[0].severity == "HIGH"


def test_unrepresented_language_is_not_missing(tmp_path):
    # No Python anywhere in the repo: a Python SDK is not expected, so not drift.
    write(tmp_path / "api/v1/user.proto", 'syntax = "proto3";\n', mtime=T)
    write(tmp_path / "sdk/go/user.pb.go", GO_STUB, mtime=T + 60)
    assert scan(tmp_path) == []


def test_no_missing_sdk_without_any_stub_in_repo(tmp_path):
    write(tmp_path / "api/v1/user.proto", 'syntax = "proto3";\n')
    assert scan(tmp_path) == []


# --- clean tree -------------------------------------------------------------


def test_clean_tree_reports_nothing(tmp_path):
    for name in ("user", "order"):
        text = f'syntax = "proto3";\n// {name}\n'
        write(tmp_path / f"api/v1/{name}.proto", text, mtime=T)
        write(tmp_path / f"sdk/go/{name}.pb.go", GO_STUB.replace("user", name), mtime=T + 60)
        write(tmp_path / f"sdk/py/{name}_pb2.py", PY_STUB, mtime=T + 60)
        write(tmp_path / f"sdk/py/{name}_pb2_grpc.py", PY_STUB, mtime=T + 60)
        write(tmp_path / f"sdk/ts/{name}_pb.js", TS_STUB.replace("user", name), mtime=T + 60)
        write(tmp_path / f"sdk/ts/{name}_pb.d.ts", TS_STUB.replace("user", name), mtime=T + 60)
        write(tmp_path / f"sdk/rust/{name}.rs", RS_STUB, mtime=T + 60)
    assert scan(tmp_path) == []
