"""Drift detection. See README.md for what each drift type means."""

from __future__ import annotations

import os
import re
import tomllib
from dataclasses import dataclass, field
from pathlib import Path

SEVERITIES = {"stale": "CRITICAL", "missing_sdk": "HIGH", "orphan": "MEDIUM"}

# protoc (Go/Java), ts-proto and grpc_tools emit the source path in a header
# comment. prost emits no path, so .rs files are matched by filename and only
# count as stubs when prost's marker comment is present (hand-written Rust in
# the same tree must not be mistaken for generated output).
_SOURCE_RE = re.compile(r"source:\s*\"?([\w./\\-]+\.proto)\"?")
_PROST_RE = re.compile(r"^//.*@generated by prost-build", re.MULTILINE)

# filename convention per language: (suffix, is_rust_marker_required)
_PATTERNS = {
    "go": (".pb.go",),
    "python": ("_pb2_grpc.py", "_pb2.py"),
    "typescript": ("_pb.js", "_pb.d.ts", "_pb.ts"),
    "rust": (".rs",),
}
_STEMS = {".pb.go": ".pb.go", "_pb2_grpc.py": "_pb2_grpc.py", "_pb2.py": "_pb2.py",
          "_pb.js": "_pb.js", "_pb.d.ts": "_pb.d.ts", "_pb.ts": "_pb.ts", ".rs": ".rs"}
# Directories never worth walking: noise, vendored output, or VCS internals.
SKIP_DIRS = frozenset(
    {".git", ".hg", ".svn", "node_modules", "__pycache__", ".venv", "venv",
     "target", "dist", "build", ".mypy_cache", ".pytest_cache", ".ruff_cache", ".tox"}
)


@dataclass
class Finding:
    type: str
    severity: str
    language: str
    proto: str  # repo-relative; "" when the proto is gone (orphan)
    stub: str
    detail: str


@dataclass
class Mapping:
    stub: Path
    language: str
    proto: Path | None
    reason: str  # "header" | "convention" | ""
    ambiguous: bool = False


@dataclass
class Tree:
    root: Path
    protos: dict[str, Path] = field(default_factory=dict)  # stem -> path
    proto_paths: list[Path] = field(default_factory=list)
    stubs: list[Path] = field(default_factory=list)
    languages: set[str] = field(default_factory=set)


def _iter_files(root: Path, suffixes: tuple[str, ...]):
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = sorted(d for d in dirnames if d not in SKIP_DIRS)
        for name in sorted(filenames):
            if name.endswith(suffixes):
                yield Path(dirpath) / name


def language_of(path: Path) -> str | None:
    for language, suffixes in _PATTERNS.items():
        if path.name.endswith(suffixes):
            return language
    return None


def stub_stem(name: str) -> str:
    for suffix in _STEMS:
        if name.endswith(suffix):
            return name[: -len(suffix)]
    return name


def _resolve(raw: str, tree: Tree) -> Path | None:
    """Header paths are relative to some proto root; try the root, then any suffix match."""
    candidate = tree.root / raw
    if candidate.is_file():
        return candidate
    for proto in tree.proto_paths:
        if proto.as_posix().endswith("/" + raw.lstrip("./")) or proto.name == Path(raw).name:
            return proto
    return None


def _head(path: Path, lines: int = 40) -> str:
    """First `lines` lines of a generated file: the only place its header lives."""
    try:
        with path.open("r", encoding="utf-8", errors="replace") as handle:
            return "".join(handle.readline() for _ in range(lines))
    except OSError:
        return ""


def is_generated(path: Path) -> bool:
    # prost writes no source path, and hand-written Rust lives in the same tree,
    # so its marker comment is the only honest way to tell generated from not.
    return bool(_PROST_RE.search(_head(path, 5))) if language_of(path) == "rust" else True


def map_stub(tree: Tree, stub: Path) -> Mapping:
    language = language_of(stub) or ""
    if not is_generated(stub):
        return Mapping(stub, language, None, "")
    match = _SOURCE_RE.search(_head(stub))
    if match:
        proto = _resolve(match.group(1), tree)
        return Mapping(stub, language, proto, "header" if proto else "")
    stem = stub_stem(stub.name)
    matches = [p for p in tree.proto_paths if p.stem == stem]
    if len(matches) == 1:
        return Mapping(stub, language, matches[0], "convention")
    return Mapping(stub, language, None, "", ambiguous=len(matches) > 1)


def discover(root: Path, cfg: dict | None = None) -> Tree:
    root = Path(root).resolve()
    cfg = cfg or {}
    proto_roots = [root / p for p in cfg.get("protos", {}).get("paths", [])] or [root]
    tree = Tree(root=root)
    for proto_root in proto_roots:
        for path in _iter_files(proto_root, (".proto",)):
            if path not in tree.proto_paths:
                tree.proto_paths.append(path)
    tree.protos = {p.stem: p for p in tree.proto_paths}
    sdk_roots = [root / s["path"] for s in cfg.get("sdk", {}).values() if s.get("path")] or [root]
    suffixes = tuple(s for group in _PATTERNS.values() for s in group)
    for sdk_root in sdk_roots:
        for path in _iter_files(sdk_root, suffixes):
            language = language_of(path)
            if language and is_generated(path) and path not in tree.stubs:
                tree.stubs.append(path)
                tree.languages.add(language)
    tree.stubs.sort()
    return tree


def scan(root: Path, cfg: dict | None = None) -> list[Finding]:
    tree = discover(root, cfg)

    def rel(path: Path) -> str:
        return path.relative_to(tree.root).as_posix()

    mappings = [m for m in (map_stub(tree, s) for s in tree.stubs) if m.proto is not None or not m.ambiguous]
    findings: list[Finding] = []

    for m in mappings:
        if m.proto is None:
            findings.append(Finding("orphan", SEVERITIES["orphan"], m.language, "", rel(m.stub),
                                    "source .proto no longer exists in the repo"))
        elif m.proto.stat().st_mtime_ns > m.stub.stat().st_mtime_ns:
            findings.append(Finding("stale", SEVERITIES["stale"], m.language, rel(m.proto), rel(m.stub),
                                    f".proto modified after stub (mapped by {m.reason})"))

    if tree.stubs:
        covered = {(rel(m.proto), m.language) for m in mappings if m.proto is not None}
        for proto in tree.proto_paths:
            for language in sorted(tree.languages):
                if (rel(proto), language) not in covered:
                    findings.append(Finding("missing_sdk", SEVERITIES["missing_sdk"], language, rel(proto), "",
                                            f"no {language} stub in repo"))
    return findings


def load_config(root: Path) -> dict:
    path = Path(root) / ".proto-drift.toml"
    if path.is_file():
        with path.open("rb") as handle:
            return tomllib.load(handle)
    return {}